//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Accounting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATS.Accounting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الحسابات.
        /// </summary>
        internal static string Account_Explorer_Title {
            get {
                return ResourceManager.GetString("Account_Explorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسـاب.
        /// </summary>
        internal static string AccountEditor_Title {
            get {
                return ResourceManager.GetString("AccountEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة العملات.
        /// </summary>
        internal static string Currency_Explorer_Title {
            get {
                return ResourceManager.GetString("Currency_Explorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملة.
        /// </summary>
        internal static string CurrencyEditor_Title {
            get {
                return ResourceManager.GetString("CurrencyEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DBAccountingC_Template {
            get {
                object obj = ResourceManager.GetObject("DBAccountingC_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ غير متوقع، سوف يتم اغلاق البرنامج.
        /// </summary>
        internal static string ErrorMsg001 {
            get {
                return ResourceManager.GetString("ErrorMsg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act Files (*.act)|*.act|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileDialog_Filter1 {
            get {
                return ResourceManager.GetString("FileDialog_Filter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة قيود اليومية.
        /// </summary>
        internal static string Journal_Entry_Explorer_Title {
            get {
                return ResourceManager.GetString("Journal_Entry_Explorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد يومية.
        /// </summary>
        internal static string JournalEntryEditor_Title {
            get {
                return ResourceManager.GetString("JournalEntryEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الميزانية العمومية.
        /// </summary>
        internal static string RepBlanceSheet {
            get {
                return ResourceManager.GetString("RepBlanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليومية العام.
        /// </summary>
        internal static string RepGeneral_Journal {
            get {
                return ResourceManager.GetString("RepGeneral_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأستاذ العام.
        /// </summary>
        internal static string RepGeneralLedger {
            get {
                return ResourceManager.GetString("RepGeneralLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الدخل.
        /// </summary>
        internal static string RepIncomeStatement {
            get {
                return ResourceManager.GetString("RepIncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميزان المراجعة.
        /// </summary>
        internal static string RepTrialBalanceProcess {
            get {
                return ResourceManager.GetString("RepTrialBalanceProcess", resourceCulture);
            }
        }
    }
}
